name: "hpc-aio"
version: 0.0.1
services:
  node1:
    entrypoint:
    - sleep
    - infinity
    build:
      context: environment
      target: build
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
  node2:
    entrypoint:
    - sleep
    - infinity
    build:
      context: environment
      target: build
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
