name: "hpc-aio"
version: 0.0.1
services:
  node1:
    hostname: node1
    entrypoint:
      - sleep
      - infinity
    build:
      context: environment/master
      target: build
    init: true
    volumes:
      - shared:/mount/shared
    ports:
      - 80:80
      - 22:22
  node2:
    hostname: node2
    entrypoint:
      - sleep
      - infinity
    build:
      context: environment/worker
      target: build
    init: true
    volumes:
      - shared:/mount/shared
    ports:
      - 80:80
      - 22:22
    depends_on:
      - node1
volumes:
  shared:
