name: "hpc-aio"
version: 0.0.1
services:
  node1: &app
    entrypoint:
    - sleep
    - infinity
    build:
      context: environment
      target: build
    init: true
    volumes:
      - shared:/mount/shared
  node2:
    <<: &app
volumes:
  shared:
