name: "hpc-aio"
version: 0.0.1
services:
  node1: &app
    entrypoint:
    - sleep
    - infinity
    build:
      context: environment
      target: build
    init: true
    volumes:
      - shared:/mount/shared
    ports:
      - 80:80
      - 22:22
  node2:
    <<: *app
    volumes:
      - shared:/mount/shared
    ports:
      - 80:80
      - 22:22
volumes:
  shared:
